apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sharon-rose-g/Shine-GitOps-Project.git
    targetRevision: main
    path: Retail-chart
    helm:
      values: |
        userprofile:
          activeVersion: blue
  destination:
    server: https://sharon-cluster-dns-i8b01x4a.hcp.centralindia.azmk8s.io
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
